### ISSUE TITLE
 老板你好，没有你的联系方式，只能在这里贴issue了

### ISSUE THREAD

**Issue by wnpllrzodiac** [HelloTheAsia/hellotheasia.github.io#1]
https://github.com/yjdwbj/panther-x2
这个仓库有一个kernel支持mpp
我想问一下 miniloader和他页面里面的uboot是一个东西吗？
我想刷他那个系统，不知道怎么操作。
目前是用的[这个](https://github.com/ophub/amlogic-s9xxx-armbian)repo的img 线刷maskrom刷的miniloader和img

**Comment by HelloTheAsia** [comment]
rk有两种刷机方式,一种是加载loader分区写入,就是ophub的armbian那种.还有一种是整合包.直接在升级的地方更新就行了.他这个系统可能是整合包 你升级试试.这个玩家还挺厉害的.可惜没有npu不然就齐活了
<img width="541" alt="image" src="https://github.com/user-attachments/assets/388f2d0c-8243-4076-bbb4-999fe09662b1">

**Comment by wnpllrzodiac** [comment]
你的意思一个img文件直接覆盖原来的系统就可以了？
原来我是用两个img的，一个miniloader，一个系统镜像。

**Comment by HelloTheAsia** [comment]
是的 这是编译系统时打包方式不同的原因.完整的镜像是已经把miniloader打包到镜像中了
